services:
  backend:
    build: backend
    working_dir: /backend
    ports:
      - "8000:8000"
    command: npm start
    environment:
      FRONTEND_HOST: "http://localhost:3000"
      MONGODB_USER_PASSWORD: "oGTU3K4rKEaJyQmP"
      SESSION_SECRET_KEY: 'ootd is amazing'

  frontend:
    build: frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NEXT_PUBLIC_BACKEND_HOST: "http://localhost:8000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:
