services:
  backend:
    build: backend
    ports:
      - "8000:8000"
    command: npm start
    volumes:
      # Copy backend to /backend on container
      - ./backend:/backend
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend:/frontend
