import type { Metadata } from "next";
import "@/app/globals.css";
import NavBar from "@/app/components/nav-bar";
import AuthCheck from "../components/auth-check";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthCheck>
          <main>
            {children}
          </main>
          <NavBar />
        </AuthCheck>
      </body>
    </html>
  );
}
