# From https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner

name: Typecheck
on:
  pull_request:
permissions:
  contents: read
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Typecheck backend
        run: npm install && npx tsc
        working-directory: backend
      - name: Typecheck frontend
        run: npm install && npx tsc
        working-directory: frontend
