# From https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner

name: Typecheck code
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --only=dev
        working-directory: backend
      - run: npx tsc
        working-directory: backend
      - run: npm install --only=dev
        working-directory: frontend
      - run: npx tsc
        working-directory: frontend
